events { worker_connections 1024; }

http {
  upstream eshop {
    server eshop-web:8080;
  }

  server {
    listen 80;
    location / {
      proxy_pass http://eshop;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
